### ISSUE TITLE
istio hook failed: "install"

### ISSUE THREAD

**Issue by hazem-soussi** [canonical/bundle-kubeflow#767] opened 2023-11-29 21:31 UTC
### Bug Description

I'm deploying charmed k8s in wich i've wanted to deploy the istio charmed but unfortunally i'm getting the hook failed install 

Unit                              Workload  Agent  Address          Ports  Message
istio-ingressgateway-operator/0*  waiting   idle   192.168.246.195         List of istio-pilot versions not found for apps: istio-pilot
istio-pilot/0*                    error     idle   192.168.126.132         hook failed: "install"
metallb/0*                        active    idle   192.168.246.194         Ready

### To Reproduce

Unit                              Workload  Agent  Address          Ports  Message
istio-ingressgateway-operator/0*  waiting   idle   192.168.246.195         List of istio-pilot versions not found for apps: istio-pilot
istio-pilot/0*                    error     idle   192.168.126.132         hook failed: "install"
metallb/0*                        active    idle   192.168.246.194         Ready

### Environment

On lxd
and i'm using charmed k8s latest version

### Relevant Log Output

```shell
unit-istio-pilot-0: 22:27:12 WARNING unit.istio-pilot/0.install - Pruning removed resources2023-11-29T21:27:12.089025Z       warn    installer       retrieving resources to prune type autoscaling/v2beta1, Kind=HorizontalPodAutoscaler: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1" not found
unit-istio-pilot-0: 22:27:12 WARNING unit.istio-pilot/0.install 2023-11-29T21:27:12.540978Z     warn    installer   retrieving resources to prune type policy/v1beta1, Kind=PodDisruptionBudget: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1" not found
unit-istio-pilot-0: 22:27:14 WARNING unit.istio-pilot/0.install Error: failed to install manifests: errors occurred during operation
unit-istio-pilot-0: 22:27:14 ERROR unit.istio-pilot/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 204, in <module>
    main(Operator)
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/main.py", line 404, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 732, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-istio-pilot-0/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 52, in install
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./istioctl', 'install', '-y', '-s', 'profile=minimal', '-s', 'values.global.istioNamespace=metallb-system']' returned non-zero exit status 1.
unit-istio-pilot-0: 22:27:14 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
unit-istio-pilot-0: 22:27:14 INFO juju.worker.uniter awaiting error resolution for "install" hook
model-6bf704fb-be57-4667-83c3-b92938b9a868: 22:27:38 INFO juju.kubernetes.klog Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
unit-istio-pilot-0: 22:27:08 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-istio-pilot-0: 22:27:08 INFO unit.istio-pilot/0.juju-log Running legacy hooks/install.
unit-istio-pilot-0: 22:27:10 WARNING unit.istio-pilot/0.install
unit-istio-pilot-0: 22:27:11 WARNING unit.istio-pilot/0.install - Processing resources for Istio core.
unit-istio-pilot-0: 22:27:11 WARNING unit.istio-pilot/0.install ✔ Istio core installed
unit-istio-pilot-0: 22:27:11 WARNING unit.istio-pilot/0.install - Processing resources for Istiod.2023-11-29T21:27:11.932949Z        error   installer       failed to update resource with server-side apply for obj PodDisruptionBudget/metallb-system/istiod: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
unit-istio-pilot-0: 22:27:12 WARNING unit.istio-pilot/0.install 2023-11-29T21:27:12.023277Z     error   installer   failed to update resource with server-side apply for obj HorizontalPodAutoscaler/metallb-system/istiod: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
```

**Comment by hazem-soussi** [comment] 2023-11-30 14:13
@NohaIhab  i really appreciate your interaction and cotnributing
Attached you'll find all the deployment description 
Concerning ISTIO i've used the latest version available on the charmhub ( juju deploy istio )



```
root@hazem-pfe:~# juju status
Model  Controller           Cloud/Region         Version  SLA          Timestamp
k8s    localhost-localhost  localhost/localhost  3.1.6    unsupported  15:10:51+01:00

App                       Version  Status       Scale  Charm                     Channel  Rev  Exposed  Message
calico                    3.25.1   active           6  calico                    stable   101  yes      Ready
containerd                1.6.8    active           6  containerd                stable    73  no       Container runtime available
easyrsa                   3.0.1    active           1  easyrsa                   stable    48  no       Certificate Authority connected.
etcd                      3.4.22   active           3  etcd                      stable   748  no       Healthy with 3 known peers
istio-pilot                        error            1  istio-pilot               stable    34  no       hook failed: "install"
kubeapi-load-balancer     1.18.0   active           3  kubeapi-load-balancer     stable    84  yes      Loadbalancer ready.
kubernetes-control-plane  1.28.4   maintenance      3  kubernetes-control-plane  stable   321  yes      Restarting snap.kube-controller-manager.daemon service
kubernetes-worker         1.28.4   active           3  kubernetes-worker         stable   134  yes      Kubernetes worker running.

Unit                         Workload     Agent  Machine  Public address  Ports         Message
easyrsa/0*                   active       idle   0        10.189.89.129                 Certificate Authority connected.
etcd/0*                      active       idle   1        10.189.89.124   2379/tcp      Healthy with 3 known peers
etcd/1                       active       idle   2        10.189.89.206   2379/tcp      Healthy with 3 known peers
etcd/2                       active       idle   3        10.189.89.139   2379/tcp      Healthy with 3 known peers
istio-pilot/1*               error        idle   15       10.189.89.186                 hook failed: "install"
kubeapi-load-balancer/0*     active       idle   4        10.189.89.91    443,6443/tcp  Loadbalancer ready.
kubeapi-load-balancer/1      active       idle   11       10.189.89.60    443,6443/tcp  Loadbalancer ready.
kubeapi-load-balancer/2      active       idle   12       10.189.89.69    443,6443/tcp  Loadbalancer ready.
kubernetes-control-plane/0   maintenance  idle   5        10.189.89.109   6443/tcp      Restarting snap.kube-controller-manager.daemon service
  calico/3                   active       idle            10.189.89.109                 Ready
  containerd/3               active       idle            10.189.89.109                 Container runtime available
kubernetes-control-plane/1*  active       idle   6        10.189.89.7     6443/tcp      Kubernetes control-plane running.
  calico/4                   active       idle            10.189.89.7                   Ready
  containerd/4               active       idle            10.189.89.7                   Container runtime available
kubernetes-control-plane/2   active       idle   10       10.189.89.148   6443/tcp      Kubernetes control-plane running.
  calico/5                   active       idle            10.189.89.148                 Ready
  containerd/5               active       idle            10.189.89.148                 Container runtime available
kubernetes-worker/0          active       idle   7        10.189.89.205   80,443/tcp    Kubernetes worker running.
  calico/2                   active       idle            10.189.89.205                 Ready
  containerd/2               active       idle            10.189.89.205                 Container runtime available
kubernetes-worker/1          active       idle   8        10.189.89.225   80,443/tcp    Kubernetes worker running.
  calico/1                   active       idle            10.189.89.225                 Ready
  containerd/1               active       idle            10.189.89.225                 Container runtime available
kubernetes-worker/2*         active       idle   9        10.189.89.172   80,443/tcp    Kubernetes worker running.
  calico/0*                  active       idle            10.189.89.172                 Ready
  containerd/0*              active       idle            10.189.89.172                 Container runtime available

Machine  State    Address        Inst id         Base          AZ  Message
0        started  10.189.89.129  juju-5ce5c0-0   ubuntu@22.04      Running
1        started  10.189.89.124  juju-5ce5c0-1   ubuntu@22.04      Running
2        started  10.189.89.206  juju-5ce5c0-2   ubuntu@22.04      Running
3        started  10.189.89.139  juju-5ce5c0-3   ubuntu@22.04      Running
4        started  10.189.89.91   juju-5ce5c0-4   ubuntu@22.04      Running
5        started  10.189.89.109  juju-5ce5c0-5   ubuntu@22.04      Running
6        started  10.189.89.7    juju-5ce5c0-6   ubuntu@22.04      Running
7        started  10.189.89.205  juju-5ce5c0-7   ubuntu@22.04      Running
8        started  10.189.89.225  juju-5ce5c0-8   ubuntu@22.04      Running
9        started  10.189.89.172  juju-5ce5c0-9   ubuntu@22.04      Running
10       started  10.189.89.148  juju-5ce5c0-10  ubuntu@22.04      Running
11       started  10.189.89.60   juju-5ce5c0-11  ubuntu@22.04      Running
12       started  10.189.89.69   juju-5ce5c0-12  ubuntu@22.04      Running
15       started  10.189.89.186  juju-5ce5c0-15  ubuntu@20.04      Running

```

**Comment by DnPlas** [comment] 2024-01-24 14:25
Hi @hazem-soussi, the error message you are getting (`subprocess.CalledProcessError: Command '['./istioctl', 'install', '-y', '-s', 'profile=minimal', '-s', 'values.global.istioNamespace=metallb-system']' returned non-zero exit status 1.`) is usually caused by the `istio-pilot` charm not being able to install the Istio control plane properly, one of the most common causes is if your k8s cluster already had an Istio control plane installed previously and it was not properly removed. Could you please confirm if that's your case?
A way to resolve this would be to use the [`istioctl`](https://istio.io/latest/docs/reference/commands/istioctl/) tool, which can help you diagnose the cause of the issue. Another solution would be to cleanup your environment making sure no trace of istio is left behind (services, pods, deployments, etc.) and re-deploy again the `istio-pilot` charm.

**Comment by hazem-soussi** [comment] 2024-04-18 17:33
@DnPlas thanks a lot issue was resolved

**Comment by DnPlas** [comment] 2024-05-27 10:39
Thanks @hazem-soussi for confirming. Closing this as the issue was resolved, but feel free to re-open or report other issues.

**Closed by DnPlas** 2024-05-27 10:39 UTC
Labels: bug
