### ISSUE TITLE
Unable to run kubeflow built-in pipeline examples

### ISSUE THREAD

**Issue by camille-rodriguez** [canonical/bundle-kubeflow#479] opened 2022-08-26 21:21 UTC
Hi, I've deployed kubeflow 1.4 on microk8s and when I try to run the Control Structures pipeline example, I hit this issue:

`
Run creation failed
{"error":"Failed to create a new run.: Failed to fetch workflow spec manifest.: ResourceNotFoundError: WorkflowSpecManifest Control-Structures-1 not found.","code":5,"message":"Failed to create a new run.: Failed to fetch workflow spec manifest.: ResourceNotFoundError: WorkflowSpecManifest Control-Structures-1 not found.","details":[{"@type":"type.googleapis.com/api.Error","error_message":"WorkflowSpecManifest Control-Structures-1 not found.","error_details":"Failed to create a new run.: Failed to fetch workflow spec manifest.: ResourceNotFoundError: WorkflowSpecManifest Control-Structures-1 not found."}]}
`

It looks like it's expecting to find a manifest with the name of the run "Control-Structure-1".  Similar thing is found in the kfi-api pod logs:

`
I0826 21:13:11.732817       6 interceptor.go:29] /api.ExperimentService/GetExperiment handler starting
I0826 21:13:11.734389       6 util.go:313] Getting user identity...
I0826 21:13:11.734412       6 util.go:323] User: admin, ResourceAttributes: &ResourceAttributes{Namespace:admin,Verb:get,Group:pipelines.kubeflow.org,Version:v1beta1,Resource:experiments,Subresource:,Name:Control Structures Experiment,}
I0826 21:13:11.734428       6 util.go:324] Authorizing request...
I0826 21:13:11.739216       6 util.go:331] Authorized user 'admin': &ResourceAttributes{Namespace:admin,Verb:get,Group:pipelines.kubeflow.org,Version:v1beta1,Resource:experiments,Subresource:,Name:Control Structures Experiment,}
I0826 21:13:11.740372       6 interceptor.go:37] /api.ExperimentService/GetExperiment handler finished
I0826 21:13:15.332027       6 interceptor.go:29] /api.PipelineService/ListPipelines handler starting
I0826 21:13:15.334213       6 interceptor.go:37] /api.PipelineService/ListPipelines handler finished
I0826 21:13:17.776170       6 interceptor.go:29] /api.PipelineService/GetPipelineVersion handler starting
I0826 21:13:17.779806       6 interceptor.go:37] /api.PipelineService/GetPipelineVersion handler finished
I0826 21:13:25.734520       6 interceptor.go:29] /api.RunService/CreateRun handler starting
I0826 21:13:25.737005       6 util.go:313] Getting user identity...
I0826 21:13:25.737026       6 util.go:323] User: admin, ResourceAttributes: &ResourceAttributes{Namespace:admin,Verb:create,Group:pipelines.kubeflow.org,Version:v1beta1,Resource:runs,Subresource:,Name:Control-Structures-1,}
I0826 21:13:25.737041       6 util.go:324] Authorizing request...
I0826 21:13:25.742126       6 util.go:331] Authorized user 'admin': &ResourceAttributes{Namespace:admin,Verb:create,Group:pipelines.kubeflow.org,Version:v1beta1,Resource:runs,Subresource:,Name:Control-Structures-1,}
I0826 21:13:25.743466       6 error.go:247] ResourceNotFoundError: WorkflowSpecManifest Control-Structures-1 not found.
github.com/kubeflow/pipelines/backend/src/common/util.NewResourceNotFoundError
	/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:159
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).CreateRun
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/resource/resource_manager.go:365
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).CreateRun
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:135
github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler.func1
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2162
main.apiServerInterceptor
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30
github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2164
google.golang.org/grpc.(*Server).processUnaryRPC
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210
google.golang.org/grpc.(*Server).handleStream
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
Failed to fetch workflow spec manifest.
github.com/kubeflow/pipelines/backend/src/common/util.(*UserError).wrap
	/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:240
github.com/kubeflow/pipelines/backend/src/common/util.Wrap
	/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:273
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).CreateRun
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/resource/resource_manager.go:364
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).CreateRun
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:135
github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler.func1
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2162
main.apiServerInterceptor
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30
github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2164
google.golang.org/grpc.(*Server).processUnaryRPC
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210
google.golang.org/grpc.(*Server).handleStream
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
Failed to create a new run.
github.com/kubeflow/pipelines/backend/src/common/util.(*UserError).wrap
	/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:240
github.com/kubeflow/pipelines/backend/src/common/util.Wrap
	/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:273
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).CreateRun
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:137
github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler.func1
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2162
main.apiServerInterceptor
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30
github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2164
google.golang.org/grpc.(*Server).processUnaryRPC
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210
google.golang.org/grpc.(*Server).handleStream
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
/api.RunService/CreateRun call failed
github.com/kubeflow/pipelines/backend/src/common/util.(*UserError).wrapf
	/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:235
github.com/kubeflow/pipelines/backend/src/common/util.Wrapf
	/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:260
main.apiServerInterceptor
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:32
github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2164
google.golang.org/grpc.(*Server).processUnaryRPC
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210
google.golang.org/grpc.(*Server).handleStream
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
ubuntu@ip-172-31-7-175:~$ 
`

**Comment by camille-rodriguez** [comment] 2022-08-26 21:23
Similar thing happens when I try to run the "Data passing in python components" pipeline example, 
`
Run creation failed
{"error":"Failed to create a new run.: Failed to fetch workflow spec manifest.: ResourceNotFoundError: WorkflowSpecManifest Run of [Tutorial] Data passing in python components (67c32) not found.","code":5,"message":"Failed to create a new run.: Failed to fetch workflow spec manifest.: ResourceNotFoundError: WorkflowSpecManifest Run of [Tutorial] Data passing in python components (67c32) not found.","details":[{"@type":"type.googleapis.com/api.Error","error_message":"WorkflowSpecManifest Run of [Tutorial] Data passing in python components (67c32) not found.","error_details":"Failed to create a new run.: Failed to fetch workflow spec manifest.: ResourceNotFoundError: WorkflowSpecManifest Run of [Tutorial] Data passing in python components (67c32) not found."}]}
`

**Comment by natalian98** [comment] 2022-09-02 13:04
Hello @camille-rodriguez, thanks for reporting the issue.
I tried to reproduce it but without success - I can create experiments and runs from the built-in pipeline examples and they get completed.

In order to help you better, could you share with us exact steps that led to this issue? In particular:
- What is your environment?
- Have you created an experiment first and then the run? The tutorial was updated recently. 
- Did you specify a service account while creating a run?
- Could you share the full output of kfp-api workload pod logs, so that we can see if all api services were started?

I'm sharing my steps in case you'd like to compare them.
1. Deploy kubeflow 1.4 on microk8s 1.21 (enabled addons: `dns storage rbac metallb:10.64.140.43-10.64.140.49`)
2. Navigate to Pipelines in the dashboard
3. Click on one of the built-in examples and create an experiment
4. Create a run pointing to that experiment:
![builtin-pipelines-run](https://user-images.githubusercontent.com/97316813/188149938-1e2d0215-be7e-4b3d-aceb-f5e917060738.png)

**Comment by ca-scribner** [comment] 2022-09-02 17:18
Looks like it might be raising from [here](https://github.com/kubeflow/pipelines/blob/1caa8e0d6889e50cde217a18abddb2c17df6ef6e/backend/src/apiserver/server/run_server.go#L137).  I wonder if kfp-db and minio both linked properly with kfp-api.  I **think** that would be the api failing to get the yaml from minio, but that's just a guess as I haven't dug into it deeply

**Comment by DomFleischmann** [comment] 2022-09-29 12:41
Hello @camille-rodriguez have you encountered this issue again in 1.6? If not I will proceed and close this issue.

**Comment by camille-rodriguez** [comment] 2022-09-29 15:59
Hi @DomFleischmann I haven't tested 1.6 in the same way, and I don't have the 1.4 environment up anymore - you can close for now and I will re-open it if I hit it again

**Closed** 2022-09-30 08:28 UTC
