### ISSUE TITLE
Deploy to AKS and EKS actions fail on latest/edge bundle

### ISSUE THREAD

**Issue by mvlassis** [canonical/bundle-kubeflow#1006] opened 2024-08-01 11:43 UTC
### Bug Description

The Github actions "Create AKS cluster, deploy CKF and run bundle test" and "Create EKS cluster, deploy CKF and run bundle test" on the `main` branch fail to run the Charmed Kubeflow UATs from the `main` branch. The failure is during the "Test bundle deployment" step.

### To Reproduce

1. Go to `Actions`, and then select the action named "Create AKS cluster, deploy CKF and run bundle test" or "Create EKS cluster, deploy CKF and run bundle test"
2. Use the workflow from the `main` branch, on the `latest` bundle, with the default Kubernetes version (empty field), and for the `main` branch of the Charmed Kubeflow UATs repository

### Environment

- Repository branch: `main`
- Bundle channel: `latest/edge`
- Kubernetes version: `1.29`

### Relevant Log Output

Output from the `deploy-to-aks` action (the `Test bundle deployment` step): [here](https://pastebin.canonical.com/p/SXxX8MdkMr/)

Output from the `deploy-to-eks` action (the `Test bundle deployment` step): [here](https://pastebin.canonical.com/p/N5bjJvNmxK/)

**Comment by DnPlas** [comment] 2024-08-01 12:14
This issue should be fixed by https://github.com/canonical/bundle-kubeflow/pull/1001. There we are checking if the deployed bundle is 1.8 to wait for the `oidc-gatekeeper` charm to go to BlockedStatus; otherwise it should pass.

**Comment by DnPlas** [comment] 2024-08-01 12:15
Closing as a duplicate of #997

**Closed by DnPlas** 2024-08-01 12:15 UTC
Labels: bug
