### ISSUE TITLE
Installing Kubeflow in an environment with a proxy fails

### ISSUE THREAD

**Issue by marowid** [canonical/bundle-kubeflow#541] opened 2023-01-31 12:16 UTC
Katib-ui is stuck in the executing state for too long and relationship data are not available for istio-pilot if installed in an environment that requires a proxy to connect to the internet. The pods created out of katib-operator are not getting environment variables responsible for the proxy setting.
https://github.com/canonical/katib-operators/tree/main/charms/katib-ui

Only workaround is to:
Attach the debug-hook to the katib-ui
On another screen - log into the K8s worker node that runs this and kill the katib-ui caasoperator process
On previous screen the debug mode should be enabled. Configure proxy settings for the Pod and run ./dispatch
Exit the debug-hook
User juju resolved to process rest of the events
#screen 1
juju debug-hooks katib-ui/0

#screen 2
juju ssh worker-p-ma-01
ps aux | grep 'application-name=katib-ui'
sudo kill -9 <PID>

#screen 1 in debug-hook console
http_proxy="http://ip:8000/" https_proxy="http://ip:8000/" ./dispatch
#CTRL+d a
juju resolved katib-ui/0

And then installation continues as normal.

Environment:
juju 2.9.37
K8s: charmed K8s 1.24
KF bundle: 1.6 stable

**Comment by andreeamun** [comment] 2023-02-13 09:26
@marowid , could you please help with these:
- Does it affect pod spec charms, sidecar charms or both?
- Which containers are and are not getting the right proxy variables set

**Comment by ca-scribner** [comment] 2023-02-13 22:03
This is caused by katib-ui using an outdated version of serialised-data-interface.

For our KF 1.6 release and before, `katib-ui` used `serialised-data-interface==0.2.2` which **did not properly handle proxy environments**.  That version did not know to look for the typical proxy environment variables that Juju will pass along to a charm environment (`JUJU_CHARM_HTTPS_PROXY`, etc), and instead just relied on whatever `requests.get()` might find on its own (which I think is why the above described hack of running `http_proxy=xyz dispatch` works).  The reason we only experienced this problem with katib-ui and not with other charms in the same environment is that other charms used the more recent `serialized-data-interface==0.3.5`, which **is** proxy aware and picks up on the proxy variables passed by Juju.

To prove the explanation above, I:
* reproduced the issue by deploying Charmed Kubernetes in vsphere (behind a squid proxy), demonstrating that katib-ui gets stuck in the same place as described above
* `juju remove-application katib-ui`
* built and deployed a local version of katib-ui that is the same as the 1.6 release except that it uses `sdi==0.3.5`
* `juju relate katib-ui:ingress istio-pilot:ingress`
* confirmed the relation data is exchanged successfully and that istio-pilot is not stuck waiting

Because the fix needed here is to update to `serialized-data-interface==0.3.5`, this bug is actually already fixed in the present repo ([see here](https://github.com/canonical/katib-operators/blob/ffb2d50b57f7049bd9b040c059fe24f4e9b30369/charms/katib-ui/requirements.txt#L71)).  This was fixed when we updated how we managed packages a few months ago, which bumped the sdi version.  KF 1.7 will release with this fixed version of the charm that properly handles proxy environments.  Because of this, no further action is needed and I'm closing this issue.

If we need a backport fix to for KF 1.6, lets open a separate issue and tackle it there.  It would be a quick job.

**Closed by ca-scribner** 2023-02-13 22:03 UTC
Labels: bug

**Comment by ca-scribner** [comment] 2023-02-13 23:51
yeah [requests proxy settings](https://requests.readthedocs.io/en/latest/user/advanced/#proxies) by default look for `http_proxy` (lowercase), so that's why the hack fix worked

**Comment by ca-scribner** [comment] 2023-02-13 23:53
for anyone facing a similar problem, looking at the env vars in the `juju debug-hook` session did show that the juju provided proxy env vars were correctly created for the hooks.

**Comment by Barteus** [comment] 2023-02-16 13:00
@ca-scribner Where can I find the task/issue that we will use to track the backporting of this into 0.14/stable?
