### ISSUE TITLE
Can't access dashboard with k3s installation

### ISSUE THREAD

**Issue by Pedrohgv** [canonical/bundle-kubeflow#389] opened 2021-08-11 12:08 UTC
Hi! I'm trying to deploy kubeflow-lite on a local machine with k3s installed. Following [this](https://charmed-kubeflow.io/docs/install) guide and changing **http://10.64.140.43.nip.io** to **http://127.0.0.1.nip.io** (not sure if this is correct, but figured 10.64.140.43 is for the microk8s use case).

`watch -c juju status --color` output is this: 
![Screenshot from 2021-08-11 08-56-03](https://user-images.githubusercontent.com/27008096/129024824-03bffd1e-c4be-4e8b-9a7b-08664ddb1460.png)

And here are the services:
![Screenshot from 2021-08-11 08-54-47](https://user-images.githubusercontent.com/27008096/129024909-e4ffb941-51d3-4581-86de-61a146cba01b.png)

As can be seen in the above picture, the `istio-ingressgateway` external IP is still "pending", even after doing the steps described in the guide.
I also watched the video in the guide and the workaround with metallb, but since the video seems to be older than the guide (which doesn't mention an external load-balancer) and I'm not using microk8s, I'm afraid trying to get metallb to work might mess my installation and break things without fixing the issue.

Also, I'm not sure if this is supposed to work, but I port-forwarded my kubeflow-dashboard to get access to it but it doesn't work. Instead, I get this weird behaviour of when I click on an item from the menu, a new identical menu pops out on the right and nothing works, with a "sorry, pipeline is not available" (in the screenshot I'm trying to access the pipeline UI):
![Screenshot from 2021-08-11 09-07-00](https://user-images.githubusercontent.com/27008096/129025810-67406d63-d9b5-497f-afbe-24d27a1b7fe1.png)

Has anyone experienced a similar issue?

Thanks in advance.

**Comment by LeoVS09** [comment] 2021-08-30 04:12
I have a similar issue with ingress and dashboard on minikube. 
I can understand possible problems with ingress can be caused by minikube, but why dashboard show `build version dev_local`? It seems like problem with container image

**Comment by maheshprabhu** [comment] 2021-09-29 08:24
Facing similar issue, @Pedrohgv were you able to resolve this issue?

**Comment by Pedrohgv** [comment] 2021-09-29 10:24
@maheshprabhu I gave up on the bundle and moved back to just the pipeline standalone feature, which was working perfectly.

**Comment by maheshprabhu** [comment] 2021-09-29 11:55
Sorry @Pedrohgv I could not get you, Can you explain in detail pls?
I am not able to access even the Notebook server.
We are facing this https://github.com/kubeflow/kubeflow/issues/6141

**Comment by Pedrohgv** [comment] 2021-09-29 13:21
Sorry for the lousy explanation @maheshprabhu. Kubeflow-pipelines is the main feature of the kubeflow bundle, and you can install it as a standalone framework. I gave on the kubeflow bundle (pipelines + other features) as I needed only the pipeline feature. Here's the main page for kubeflow-pipelines: https://www.kubeflow.org/docs/components/pipelines/pipelines-quickstart/

**Comment by maheshprabhu** [comment] 2021-09-30 05:43
Thank you @Pedrohgv Meanwhile pls post here if you are able to resolve this dashboard issue. Hopefully all issues will get resolved in v1.4

**Comment by DomFleischmann** [comment] 2021-09-30 09:04
The current way istio-ingressgateway is setup it will use the underlying ingress that has been already installed previously. In the case of microk8s this is done by enabling the ingress addon with `microk8s enable ingress`. With k3s or minikube you will have to set up ingress beforehand somehow. This is the [manifest](https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/ingress.yaml) applied for the microk8s ingress addon, it can possibly also work for k3s and minikube.

**Comment by maheshprabhu** [comment] 2021-09-30 10:01
@DomFleischmann Thanks for your inputs. We in-fact used k8s , followed this guide , enabled ingress https://www.kubeflow.org/docs/distributions/microk8s/kubeflow-on-microk8s/
But ran into this issue https://github.com/kubeflow/kubeflow/issues/6141
Any help is appreciated.

**Comment by DomFleischmann** [comment] 2021-09-30 10:33
@maheshprabhu Did you access it through the ingressgateway IP and `nip.io`?

**Comment by maheshprabhu** [comment] 2021-10-06 05:30
@DomFleischmann - yes Same issue with ingress IP and xx.nip.io as well. Getting blank page

**Closed** 2021-11-11 13:34 UTC
