### ISSUE TITLE
oidc-gatekeeper locked on CrashLoopBackOff

### ISSUE THREAD

**Issue by apulache** [canonical/bundle-kubeflow#266] opened 2020-11-14 23:18 UTC
I've just tried to install KubeFlow on MicroK8s acordding  Canonical guide found here https://ubuntu.com/kubeflow/install.

Pod idc-gatekeeper never started and stay in CrashLoopBackOff.

I've tried this with Ubuntu Server 20.04 and 18.04 and the results are the same.

Here the details gathered:

microk8s.kubectl get po --all-namespaces
================================
NAMESPACE         NAME                                           READY   STATUS             RESTARTS   AGE
kube-system       kubernetes-dashboard-7ffd448895-nvg7s          1/1     Running            3          29m
kube-system       calico-kube-controllers-847c8c99d-977dn        1/1     Running            3          31m
kube-system       dashboard-metrics-scraper-6c4568dc68-lf8vz     1/1     Running            3          29m
kube-system       nvidia-device-plugin-daemonset-dc7fk           1/1     Running            2          27m
kube-system       calico-node-rp4pz                              1/1     Running            4          31m
kube-system       hostpath-provisioner-5c65fbdb4f-dnm9p          1/1     Running            3          29m
kube-system       metrics-server-8bbfb4bdb-rkxd4                 1/1     Running            3          29m
kube-system       coredns-86f78bb79c-pd2tp                       1/1     Running            3          30m
ingress           nginx-ingress-microk8s-controller-qwcv7        1/1     Running            0          21m
metallb-system    speaker-pvtzs                                  1/1     Running            0          21m
metallb-system    controller-559b68bfd8-vps94                    1/1     Running            0          21m
controller-uk8s   controller-0                                   2/2     Running            1          20m
kubeflow          ambassador-operator-0                          1/1     Running            0          19m
kubeflow          argo-controller-operator-0                     1/1     Running            0          19m
kubeflow          argo-ui-operator-0                             1/1     Running            0          19m
kubeflow          dex-auth-operator-0                            1/1     Running            0          19m
kubeflow          jupyter-controller-operator-0                  1/1     Running            0          18m
kubeflow          argo-ui-78dfc9744-b9tcg                        1/1     Running            0          19m
kubeflow          ambassador-656dd8bf4-5cgcm                     1/1     Running            0          19m
kubeflow          jupyter-controller-66d9c5664b-tr4z8            1/1     Running            0          18m
kubeflow          katib-db-operator-0                            1/1     Running            0          18m
kubeflow          jupyter-web-operator-0                         1/1     Running            0          18m
kubeflow          katib-db-manager-operator-0                    1/1     Running            0          18m
kubeflow          katib-controller-operator-0                    1/1     Running            0          18m
kubeflow          katib-ui-operator-0                            1/1     Running            0          18m
kubeflow          kubeflow-profiles-operator-0                   1/1     Running            0          18m
kubeflow          kubeflow-dashboard-operator-0                  1/1     Running            0          18m
kubeflow          metacontroller-operator-0                      1/1     Running            0          18m
kubeflow          metadata-api-operator-0                        1/1     Running            0          17m
kubeflow          metadata-envoy-operator-0                      1/1     Running            0          17m
kubeflow          metadata-db-operator-0                         1/1     Running            0          17m
kubeflow          katib-ui-6764bfd7bc-jsjb4                      1/1     Running            0          17m
kubeflow          katib-db-0                                     1/1     Running            0          18m
kubeflow          katib-controller-6ffd875f77-pljfc              1/1     Running            0          17m
kubeflow          pipelines-persistence-operator-0               1/1     Running            0          17m
kubeflow          pipelines-scheduledworkflow-operator-0         1/1     Running            0          16m
kubeflow          pipelines-viewer-operator-0                    1/1     Running            0          16m
kubeflow          metacontroller-6d9d9696bd-2vgrq                1/1     Running            0          17m
kubeflow          oidc-gatekeeper-operator-0                     1/1     Running            0          16m
kubeflow          metadata-db-0                                  1/1     Running            0          17m
kubeflow          metadata-ui-operator-0                         1/1     Running            0          16m
kubeflow          minio-operator-0                               1/1     Running            0          16m
kubeflow          katib-db-manager-7cc8597b4d-8p64h              1/1     Running            0          17m
kubeflow          pipelines-db-operator-0                        1/1     Running            0          16m
kubeflow          pipelines-api-operator-0                       1/1     Running            0          16m
kubeflow          pipelines-ui-operator-0                        1/1     Running            0          16m
kubeflow          pipelines-visualization-operator-0             1/1     Running            0          16m
kubeflow          pytorch-operator-operator-0                    1/1     Running            0          16m
kubeflow          metadata-grpc-operator-0                       1/1     Running            0          15m
kubeflow          seldon-core-operator-0                         1/1     Running            0          15m
kubeflow          tf-job-operator-operator-0                     1/1     Running            0          15m
kubeflow          jupyter-web-784c8774d5-dfhqd                   1/1     Running            0          17m
kubeflow          pipelines-db-0                                 1/1     Running            0          15m
kubeflow          kubeflow-dashboard-5f57644995-clzwr            1/1     Running            0          17m
kubeflow          kubeflow-profiles-646d5d646f-72thv             2/2     Running            0          17m
kubeflow          metadata-api-5bfdcd776d-wn6z2                  1/1     Running            0          17m
kubeflow          pipelines-scheduledworkflow-76568f476c-w66lv   1/1     Running            0          16m
kubeflow          pipelines-viewer-6ffb7b9cf4-ggnn5              1/1     Running            0          16m
kubeflow          minio-0                                        1/1     Running            0          16m
kubeflow          dex-auth-dc6d7d996-kpqdz                       1/1     Running            0          15m
kubeflow          pytorch-operator-7b6448bb87-27h99              1/1     Running            0          14m
kubeflow          pipelines-visualization-74c8796b7f-56bq5       1/1     Running            0          15m
kubeflow          argo-controller-876844c7b-gqp4g                1/1     Running            0          15m
kubeflow          metadata-ui-55b6498cd4-h5fsp                   1/1     Running            0          14m
kubeflow          pipelines-persistence-848b5bff5-b59c9          1/1     Running            2          14m
kubeflow          pipelines-ui-6894ddf96d-d9jx8                  1/1     Running            0          14m
kubeflow          tf-job-operator-5f54dfb5b6-jd89b               1/1     Running            0          14m
kubeflow          metadata-grpc-7fd4bc757b-4k92p                 1/1     Running            0          14m
kubeflow          metadata-envoy-6cfdf75d5f-fp7bv                1/1     Running            0          13m
kubeflow          seldon-core-7fc9b755cf-p2lng                   1/1     Running            0          13m
kubeflow          oidc-gatekeeper-774f6d8997-2t7wm               0/1     CrashLoopBackOff   6          16m     (********* error here)
kubeflow          pipelines-api-6696896c7-7cszp                  1/1     Running            0          13m

microk8s.kubectl describe pod oidc-gatekeeper-774f6d8997-2t7wm --namespace kubeflow
=====================================================================
Name:         oidc-gatekeeper-774f6d8997-2t7wm
Namespace:    kubeflow
Priority:     0
Node:         kubeflow-u1805/192.168.0.233
Start Time:   Sat, 14 Nov 2020 17:47:28 -0500
Labels:       juju-app=oidc-gatekeeper
              pod-template-hash=774f6d8997
Annotations:  apparmor.security.beta.kubernetes.io/pod: runtime/default
              cni.projectcalico.org/podIP: 10.1.101.8/32
              cni.projectcalico.org/podIPs: 10.1.101.8/32
              juju.io/controller: d0d6bfd7-2457-4c3e-84a5-6d70991f0497
              juju.io/model: 273b24f9-7a3f-4a6c-8f4f-833967c046a7
              juju.io/unit: oidc-gatekeeper/0
              seccomp.security.beta.kubernetes.io/pod: docker/default
Status:       Running
IP:           10.1.101.8
IPs:
  IP:           10.1.101.8
Controlled By:  ReplicaSet/oidc-gatekeeper-774f6d8997
Init Containers:
  juju-pod-init:
    Container ID:  containerd://709611cf334fa3850851cc41102c7e000302f267a3150f906cae4a3847121033
    Image:         jujusolutions/jujud-operator:2.7.6
    Image ID:      docker.io/jujusolutions/jujud-operator@sha256:866eccf1961604db3a4710142f77632519c6627da7ebdebd26c8c17c03df48e6
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      export JUJU_DATA_DIR=/var/lib/juju
      export JUJU_TOOLS_DIR=$JUJU_DATA_DIR/tools

      mkdir -p $JUJU_TOOLS_DIR
      cp /opt/jujud $JUJU_TOOLS_DIR/jujud
      initCmd=$($JUJU_TOOLS_DIR/jujud help commands | grep caas-unit-init)
      if test -n "$initCmd"; then
      $JUJU_TOOLS_DIR/jujud caas-unit-init --debug --wait;
      else
      exit 0
      fi

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 14 Nov 2020 17:47:32 -0500
      Finished:     Sat, 14 Nov 2020 17:47:43 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/juju from juju-data-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9pbdp (ro)
Containers:
  oidc-gatekeeper:
    Container ID:   containerd://c3d56633318b35977fb4284b772d3e466a562036e5cae87c32652e2de97a7429
    Image:          registry.jujucharms.com/kubeflow-charmers/oidc-gatekeeper/oci-image@sha256:9bb01f793655259071763219c4ef34ebd01953d742b28afba8361c68bf9e3235
    Image ID:       registry.jujucharms.com/kubeflow-charmers/oidc-gatekeeper/oci-image@sha256:9bb01f793655259071763219c4ef34ebd01953d742b28afba8361c68bf9e3235
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 14 Nov 2020 18:09:14 -0500
      Finished:     Sat, 14 Nov 2020 18:09:14 -0500
    Ready:          False
    Restart Count:  8
    Environment:
      CLIENT_ID:         authservice-oidc
      CLIENT_SECRET:     VGX0VF150TTQ26EBRFPYXPI8D8WZGB
      DISABLE_USERINFO:  true
      OIDC_PROVIDER:     /dex
      OIDC_SCOPES:       profile email groups
      REDIRECT_URL:      /oidc/login/oidc
      SELF_URL:          /oidc
      SERVER_PORT:       8080
      STORE_PATH:        bolt.db
      USERID_HEADER:     kubeflow-userid
      USERID_PREFIX:
    Mounts:
      /usr/bin/juju-run from juju-data-dir (rw,path="tools/jujud")
      /var/lib/juju from juju-data-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9pbdp (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  juju-data-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-9pbdp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9pbdp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  24m                   default-scheduler  Successfully assigned kubeflow/oidc-gatekeeper-774f6d8997-2t7wm to kubeflow-u1805
  Normal   Pulled     24m                   kubelet            Container image "jujusolutions/jujud-operator:2.7.6" already present on machine
  Normal   Created    24m                   kubelet            Created container juju-pod-init
  Normal   Started    24m                   kubelet            Started container juju-pod-init
  Normal   Pulling    23m                   kubelet            Pulling image "registry.jujucharms.com/kubeflow-charmers/oidc-gatekeeper/oci-image@sha256:9bb01f793655259071763219c4ef34ebd01953d742b28afba8361c68bf9e3235"
  Normal   Pulled     18m                   kubelet            Successfully pulled image "registry.jujucharms.com/kubeflow-charmers/oidc-gatekeeper/oci-image@sha256:9bb01f793655259071763219c4ef34ebd01953d742b28afba8361c68bf9e3235" in 5m16.048310112s
  Normal   Started    18m (x4 over 18m)     kubelet            Started container oidc-gatekeeper
  Normal   Pulled     17m (x4 over 18m)     kubelet            Container image "registry.jujucharms.com/kubeflow-charmers/oidc-gatekeeper/oci-image@sha256:9bb01f793655259071763219c4ef34ebd01953d742b28afba8361c68bf9e3235" already present on machine
  Normal   Created    17m (x5 over 18m)     kubelet            Created container oidc-gatekeeper
  Warning  BackOff    3m59s (x69 over 18m)  kubelet            Back-off restarting failed container

microk8s.kubectl logs oidc-gatekeeper-774f6d8997-2t7wm --namespace kubeflow
===============================================================
time="2020-11-14T23:09:14Z" level=fatal msg="Failed to parse configuration: required key AUTHSERVICE_URL_PREFIX missing value"

According to logs there is some kind of AUTHSERVICE key missing.

By the way both installations on Ubuntu Server 20.04 and 18.04 just started 28 pods instead of the 34 display here https://www.youtube.com/watch?v=KPEGKKNB63Q&t=447s

Definitely something is missing.

Please review the issue as this is a mayor blocker that prevent the usage of KubeFlow.

Thanks in advance.

**Comment by BionixAB** [comment] 2021-01-14 13:00
Exactly the same problem.
heapster-v1.5.2 and nvidia-device-plugin-daemonset also showed problems but are now up.
ALL of the pods have had at least 2 restarts, but are currently up.
Configuration:
Ubuntu 18.04.3 LTS Clean install
INTEL NUC 8i5BEH w 8259 CPU (4+4 threads), 32GB RAM, 500GB Samsung EVO, NVIDIA-Driver 460 and Nvidia 1080 connected via Thunderbolt 3 to hp OMEN Accelerator.

**Comment by knkski** [comment] 2021-01-22 14:23
@apulache, @BionixAB: This issue should now be fixed with the latest version of MicroK8s. Can you refresh (`sudo snap refresh microk8s --channel latest/edge`), and try again?

**Comment by DomFleischmann** [comment] 2021-06-25 10:08
This issue should be fixed by now and will therefore be closed.

If you are able to reproduce this in the latest microk8s release and the issue is still relevant feel free to reopen it.

**Closed by DomFleischmann** 2021-06-25 10:08 UTC
