### ISSUE TITLE
Notebook-MLFlow integration by poddefaults exposes minio access-key and secret-key

### ISSUE THREAD

**Issue by Barteus** [canonical/bundle-kubeflow#528] opened 2022-12-09 10:38 UTC
**Current**
In the kubeflow namespace:
```
$ kubectl describe poddefaults mlflow-server-minio -n kubeflow
Name:         mlflow-server-minio
Namespace:    kubeflow
Labels:       app.kubernetes.io/managed-by=juju
              app.kubernetes.io/name=admission-webhook
API Version:  kubeflow.org/v1alpha1
Kind:         PodDefault
Spec:
  Env:
    Name:   AWS_ACCESS_KEY_ID
    Value:  minio123
    Name:   AWS_SECRET_ACCESS_KEY
    Value:  minio123
    Name:   MLFLOW_S3_ENDPOINT_URL
    Value:  http://minio.kubeflow:9000
    Name:   MLFLOW_TRACKING_URI
    Value:  http://mlflow-server.kubeflow.svc.cluster.local:5000
  Selector:
    Match Labels:
      Mlflow - Server - Minio:  true
Events:                         <none>
```

**Expected**
access-key and secret-key are stored as Secrets, not in the open text

**Comment by ca-scribner** [comment] 2022-12-09 14:32
This might be happening due to [this line](https://github.com/canonical/mlflow-operator/blob/6d7b891bb3af07c460489b59803c07cd853af82f/charms/mlflow-server/src/charm.py#L95), which I believe asks admission-webhook to create a `PodDefault` with the minio credentials.  We should look at removing this, as initialising credentials via a `PodDefault` will by definition never be obscured (the plaintext password will always be written into the pod spec that the PodDefault modifies).

An alternate approach could be to create a `PodDefault` that, rather than explicitly defining minio's credentials, instead references credentials in an existing secret.  This would require the secret referenced to exist in the user's profile.  We do something similar [in kubeflow pipelines](https://github.com/canonical/kfp-operators/commit/c974456ad17e48e469a4b98df2b14219b50a8060), but in that case we already have a process (the sync.py CompositeController) that puts data into user's namespaces automatically.  We don't have a similar setup here, so we'd have to do it manually or build out that automation.

**Comment by i-chvets** [comment] 2023-01-06 19:45
Main fix design points:
- `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` specified in `config.yaml` as secrets.
- Modify code to get those values from `config`
- Add note to README that indicates that secrets need to be created in user namespace prior to integration of MLFlow. Update any other documentation as well.

**Comment by Barteus** [comment] 2023-01-10 10:19
Why do we need to create them manually when we have a relation? Can juju/charm create secrets? 
We are already creating a secret for each charm.

**Comment by i-chvets** [comment] 2023-01-10 13:11
> Why do we need to create them manually when we have a relation? Can juju/charm create secrets? We are already creating a secret for each charm.

The secret needs to be in user namespace. We cannot do that at the time of deployment. @ca-scribner explained the issue above.

**Comment by ca-scribner** [comment] 2023-01-10 18:55
I'd leave how mlflow's charm gets the minio credentials as is (it gets them through a relation with the minio charm, and I think that already works ok).  The trouble here is how we get those credentials to users.  Currently, the charm tries to get those creds to users through a PodDefault which will never be secure, so that needs to be removed (and we can remove the relation to admission-webhook entirely).

In place of that, I think @i-chvets is correct that we need to manually create the secrets for all users.  @Barteus is correct that we already have the credentials in a charm and from juju can create secrets, but the problem is that none of our charms know the concept of a Kubeflow user (or really, `Profile`), so while we can create secrets our charms dont know where they should be created.  

To make the user experience a little better, I think @NohaIhab's work on [automating user creation](https://docs.google.com/document/d/1Cht_4eODd3y_s_w_S70Ys28f_jEdqT-T3hYgkdp6X-Q/edit) (she can give a better update as to status) would be useful here.  So the steps that @i-chvets suggests we document could also be done automatically by the user creation.

**Comment by ca-scribner** [comment] 2023-01-10 18:59
There's one possible hack we could use if we are ok sacraficing a small bit of maintenance for a smoother user experience.  

The [kubeflow pipelines profile controller](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-profile-controller) creates in every user's namespace a secret with the minio credentials that kfp uses.  Although it doesn't have to be, it is very likely that the minio for kfp will be the same as the minio used for mlflow.  So we could just reuse the secret that every user already has.  The downside being that this only works by coincidence, rather than design.  There's no requirement that mlflow be connected to the same minio as kfp

**Comment by i-chvets** [comment] 2023-01-10 19:43
@Barteus Please confirm if that's the deployment scenario we are addressing here. It basically limits MLFlow integration to use the same minio/S3 endpoint as KFP. Will there be a need to have MLFlow to point to some other S3 endpoint other than the one KFP points to?

**Comment by i-chvets** [comment] 2023-01-10 19:48
Creating secrets manually in user namespace could be sufficient for now. When automated user creation feature will come in we will ensure that those secrets are created automatically. No changes to MLFlow should be required then.

**Comment by ca-scribner** [comment] 2023-01-10 19:51
Minor nit that I think you'll hit during implementation: I think we'd want to modify the MLFlow charm code to request a PodDefault that points to the secret, rather than MLFlow to point directly to the secret.  The PodDefault is the mechanism for how we can get user notebooks to automatically have these extra settings.  We do something similar as-is for kfp settings

And yes, I realise 2 posts ago I said we should remove the PodDefault relation entirely.  I think I was wrong back then :)

**Comment by i-chvets** [comment] 2023-01-12 01:38
Consensus for fixing this issue is to remove AWS credentials from pod defaults.
Need to keep pod default to have other environment variables set.

**Comment by i-chvets** [comment] 2023-01-13 14:31
Fix is merged.

**Comment by i-chvets** [comment] 2023-01-16 16:55
Launchpad https://bugs.launchpad.net/kubeflow-bundle/+bug/2000911

**Comment by i-chvets** [comment] 2023-01-17 00:43
Additional discussion in PR https://github.com/canonical/mlflow-operator/pull/92

**Comment by i-chvets** [comment] 2023-01-30 20:44
Tested. No open-text AWS credentials in poddefaults:
```
$ microk8s.kubectl describe poddefaults mlflow-server-minio -n kubeflow
Name:         mlflow-server-minio
Namespace:    kubeflow
Labels:       app.kubernetes.io/managed-by=juju
              app.kubernetes.io/name=admission-webhook
Annotations:  controller.juju.is/id: 73f99ff9-2305-48ac-8b60-fd1d60a44d06
              model.juju.is/id: bcecb8db-6b4c-4c78-86b6-5b1b286d6fe7
API Version:  kubeflow.org/v1alpha1
Kind:         PodDefault
Metadata:
  Creation Timestamp:  2023-01-30T20:21:10Z
  Generation:          2
  Managed Fields:
    API Version:  kubeflow.org/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:controller.juju.is/id:
          f:model.juju.is/id:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
      f:spec:
        .:
        f:env:
        f:selector:
          .:
          f:matchLabels:
            .:
            f:mlflow-server-minio:
    Manager:         jujud
    Operation:       Update
    Time:            2023-01-30T20:21:10Z
  Resource Version:  21883
  Self Link:         /apis/kubeflow.org/v1alpha1/namespaces/kubeflow/poddefaults/mlflow-server-minio
  UID:               d9f703b4-b7ea-4b11-aa2a-d2c7aad19818
Spec:
  Env:
    Name:   MLFLOW_S3_ENDPOINT_URL
    Value:  http://minio.kubeflow:9000
    Name:   MLFLOW_TRACKING_URI
    Value:  http://mlflow-server.kubeflow.svc.cluster.local:5000
  Selector:
    Match Labels:
      Mlflow - Server - Minio:  true
Events:                         <none>
```

**Closed** 2023-03-01 21:08 UTC
Labels: bug
