### ISSUE TITLE
kubeflow-lite bundle references to charm-store

### ISSUE THREAD

**Issue by paulomach** [canonical/bundle-kubeflow#434] opened 2022-02-14 15:08 UTC
Hello,

Deployment of kubeflow-lite with bundle failed with the "argo-controller" not being found.
Pretty sure that's related to the cs -> ch migration, since I was able to fix it overlaying  with the argo-controller referencing ch, i.e.:

`  argo-controller:               { charm: ch:argo-controller,         channel: latest/stable, scale: 1 }`

I'm using juju version `2.9.22-ubuntu-amd64`

There's a proposed [PR](https://github.com/canonical/bundle-kubeflow/pull/435) to workaround this.

**Comment by DnPlas** [comment] 2022-02-15 00:43
Hi @paulomach, thanks for the report. This looks like a transient issue, but just to be sure, do you mind sharing the logs or error msg you are getting when deploying the bundle as well as the steps to reproduce? Logs from `juju status` or `juju debug-log` are helpful.
I tried reproducing the issue running `juju deploy kubeflow-lite` without success.

**Comment by DomFleischmann** [comment] 2022-02-15 08:38
There was an issue with argo-controller during the migration from Charmstore to Charmhub, this was fixed by the Charmhub team yesterday. Therefore it should not be an issue anymore.

Please reopen if it occurs again.

**Closed by DomFleischmann** 2022-02-15 08:38 UTC
