### ISSUE TITLE
Kaggle image does not work correctly with this bundle

### ISSUE THREAD

**Issue by aym-frikha** [canonical/bundle-kubeflow#119] opened 2019-10-24 14:48 UTC
Following this tutorial for Kaggle: https://github.com/canonical-labs/kaggle-kubeflow-tutorial

I was unable to access Kaggle notebook after creating it: the error I have in the browser " upstream connect error or disconnect/reset before headers "

**Comment by DomFleischmann** [comment] 2021-06-25 09:41
With this issue being almost 2 years old and Charmed Kubeflow having changed a lot we will close this issue.

If you are able to reproduce this in the latest kubeflow bundle and the issue is still relevant feel free to reopen it.

**Closed by DomFleischmann** 2021-06-25 09:41 UTC
