### ISSUE TITLE
UnitsAvailable alerts are firing constantly

### ISSUE THREAD

**Issue by facundofc** [canonical/bundle-kubeflow#564] opened 2023-03-27 16:48 UTC
On a recent deployment we're seeing these alerts firing all the time (literally, stuck to "firing"):

- ArgoUnitIsUnavailable
- DexAuthUnitIsUnavailable
- JupyterControllerUnitIsUnavailable
- MetacontrollerUnitIsUnavailable
- MinioUnitIsUnavailable
- TrainingOperatorUnitIsUnavailable

Looking at the `up` metric (which these alert rules query), we see that these are alternating between 1 and 0 every 45 seconds (this is a sample from the argo controller, query being: `up{juju_application="argo-controller",juju_..."="..."}[10m]`):

```
1 @1679925736.77
0 @1679925781.26
1 @1679925796.77
0 @1679925841.26
1 @1679925856.77
0 @1679925901.26
1 @1679925916.77
0 @1679925961.26
1 @1679925976.77
0 @1679926021.26
1 @1679926036.77
0 @1679926081.26
1 @1679926096.77
0 @1679926141.26
1 @1679926156.77
0 @1679926201.26
1 @1679926216.77
0 @1679926261.26
1 @1679926276.77
0 @1679926321.26
```

Incidentally to this flapping behavior, [the duration](https://github.com/canonical/argo-operators/blob/19f23d530a932110e109ac96c24a9ed60f8bcfd6/charms/argo-controller/src/prometheus_alert_rules/unit_unavailable.rule#L3) for these alerts (at least for argo) is set to `0m`, which seems a bit too sensitive for production envs.

**Comment by i-chvets** [comment] 2023-05-12 12:50
FIx is merged.

**Comment by facundofc** [comment] 2023-07-31 19:28
@i-chvets, the changes pushed by @dparv (changing the `for:` from 0 to `5m`) are not a fix for this issue. I believe this should be reopened as the metrics are flapping or directly stuck to 0 (as in the dex-auth case). That needs to be addressed or pointed out here where it was addressed.

Thanks!

**Comment by orfeas-k** [comment] 2023-08-09 09:08
Thank you @facundofc for letting us know about the issue not having been fixed. In order to better understand the issue, our team will need some more information.

1. Are there specific steps to follow in order to reproduce the issue?
2. Do you deploy these charms alone or through the bundle?
3. Is there a specific a test environmnet or a CI where this has run? That would be of great help too
4. What would be the expected behaviour? I understand that we don't want the flapping between 1 and 0, but what would we expect them to be? Also, should alerts should move from the `firing` stage to a next one?

**Comment by nishant-dash** [comment] 2023-12-04 12:24
Graphing those 4 alerts, for Minio, seldon controller manager, metacontroller operator anddex auth, I see they have been 0 since the beginning of the deployment (i.e they were never 1 to begin with)

**Comment by simskij** [comment] 2024-01-30 12:41
What @nishant-dash said. I'll copy in my reply from Matrix:

> if the metrics that are being scraped alternate between 1 and 0, that's a sign that something is wrong either with your exporter, or with the application itself, as it's actually producing metrics saying that it's unhealthy. So, what happens here is that the alert rule - correctly - triggers and lets you know that something fishy is going on in your charm

**Comment by DnPlas** [comment] 2024-02-04 01:48
Thanks @simskij and @nishant-dash for the insights.

#### Steps to reproduce
1. Deploy the latest supported versions of the offending charms. For example `juju deploy minio --channel ckf-1.8/stable`
2. Deploy `cos-lite` following [this guide](https://charmhub.io/topics/canonical-observability-stack/tutorials/install-microk8s)
3. Follow [this guide](https://charmed-kubeflow.io/docs/integrate-with-cos) to deploy other dependencies and add the required relations.
4. Go to the prometheus dashboard > Alerts and list all the firing alerts
![image](https://github.com/canonical/bundle-kubeflow/assets/18201737/b8ff450b-9c77-4fe6-a0f4-3fad6a57d08f)


I was able to reproduce the issue only for four (minio, metacontroller, dex, seldon) of the six applications that were originally reported in the issue. After some investigation, I did not observe any issues with the units and in fact all of the application's `Pods` were not restarted even once:

```
ubuntu@charm-dev-jammy:~/minio-operator$ kubectl get pods -nkubeflow
NAME                                            READY   STATUS    RESTARTS   AGE
modeloperator-84f4db8-gp67q                     1/1     Running   0          62m
minio-operator-0                                1/1     Running   0          61m
argo-controller-0                               2/2     Running   0          62m
grafana-agent-k8s-0                             2/2     Running   0          60m
dex-auth-0                                      2/2     Running   0          51m
istiod-6fcf5445fc-cnfzv                         1/1     Running   0          50m
istio-ingressgateway-workload-cb759595c-5ctwq   1/1     Running   0          50m
istio-pilot-0                                   1/1     Running   0          50m
istio-ingressgateway-0                          1/1     Running   0          50m
training-operator-0                             2/2     Running   0          46m
metacontroller-operator-charm-0                 1/1     Running   0          45m
metacontroller-operator-0                       1/1     Running   0          45m
jupyter-controller-0                            2/2     Running   0          44m
seldon-controller-manager-0                     2/2     Running   0          42m
minio-0                                         1/1     Running   0          6m29s
```

From the above, I started investigating each application's metrics endpoint to check what metrics were being scraped, and found out that for the four "failing" apps had misconfigurations, meaning the scraped metrics were not accurate or not reachable at alll. The following is a summary of my findings:

#### Minio

When trying to reach the metrics endpoint via `svc:9000//minio/v2/metrics/cluster` from within the minio `Pod`, I got a `403 Forbidden` msg, which meant the endpoint must've need some authorization for reaching out.
According to the [docs](https://min.io/docs/minio/kubernetes/upstream/operations/monitoring/metrics-and-alerts.html) and the [minio Prometheus setup guide](https://github.com/minio/minio/blob/master/docs/metrics/prometheus/README.md), we are supposed to set `MINIO_PROMETHEUS_AUTH_TYPE="public"` as an env variable in the container.
After setting the variable, I was able to curl the endpoint and fetch metrics. This also prevented the alert to fire constantly.

#### Dex
TODO

#### Metacontroller
TODO

#### Seldon
TODO

**Comment by DnPlas** [comment] 2024-02-04 03:28
Part of the fix of this issue will also be to refactor the integration tests for all our charms that are integrated with prometheus, as these type of errors should've been caught by that.

**Comment by DnPlas** [comment] 2024-02-07 00:37
Here are some updates after a bit more debugging

#### Dex

The was a misconfiguration on the telemetry settings for the dex workload. We need to set the `telemetry` value in dex's config file (`etc/dex/config.docker.yaml`). Alerts were firing for this charm because there was nothing listening on the metrics port that we passed to the MetricsCollector due to the missing configuration.

Fix in https://github.com/canonical/dex-auth-operator/pull/185

**Comment by DnPlas** [comment] 2024-02-08 01:17
Here are some updates after a bit more debugging

#### Training and Jupyter

For ensuring the metrics endpoint is actually reachable by the prometheus scraper, I have configured the Kubernetes Services of these applications to always expose the metrics port.

Fix for training-operator: https://github.com/canonical/training-operator/pull/151
Fix for jupyter-controller: https://github.com/canonical/notebook-operators/pull/332

#### Seldon

As mentioned before, there is a strange behaviour in seldon, as two scrape jobs are set for this application. It shows in two different places:
1. Querying the up metric in the promehteus dashboard, which returns more than one item with different job names. The job that is always 1, should be the only existing job:

```
up{instance="kubeflow_47f52a8c-c74d-4072-8e25-4865db988512_seldon-controller-manager_seldon-controller-manager/0", job="juju_kubeflow_47f52a8c_seldon-controller-manager_prometheus_scrape-0", juju_application="seldon-controller-manager", juju_charm="seldon-core", juju_model="kubeflow", juju_model_uuid="47f52a8c-c74d-4072-8e25-4865db988512", juju_unit="seldon-controller-manager/0"}  # <--- This has a bunch of 0

up{instance="kubeflow_47f52a8c-c74d-4072-8e25-4865db988512_seldon-controller-manager_seldon-controller-manager/0", job
```

2. Checking the relation data bag, I can observe the following jobs:
```
      scrape_jobs: '[{"metrics_path": "/metrics", "static_configs": [{"targets": ["seldon-controller-manager.seldon-only.svc:8080"]}],
        "scrape_interval": "30s"}, {"metrics_path": "/metrics", "static_configs":
        [{"targets": ["*:80"]}]}]'
```
This can explain why the alert is firing constantly: there is a job that is scraping metrics from `*:80/metrics` which is not a valid metrics endpoint.

After a closer inspection to the charm code, I noticed that we are setting an extra job in [L164](https://github.com/canonical/seldon-core-operator/blob/main/src/charm.py#L164). This extra job was introduced in https://github.com/canonical/seldon-core-operator/pull/94, but the reason to add this instead of just leaving the regular metrics endpoint is not clear. To fix the issue, we'll remove this extra line to avoid having a misconfigured job that is causing the `UnitsUnavailable` alert to constantly fire.

Fix for seldon: https://github.com/canonical/seldon-core-operator/pull/236

**Comment by DnPlas** [comment] 2024-02-08 01:32
#### Argo

I was not able to reproduce the issue for argo-controller. I checked the relation data, the metrics endpoint and ensure it is reachable from the prometheus scraper. In the prometheus dashboard, I made a query for the unit and it stays at a constant `1`. It is possible that recent changes in the charm code helped fixing the issue. Should this issue be present again for argo, let's file a separate issue.

**Comment by DnPlas** [comment] 2024-02-08 02:53
#### Summary and conclusions

* Alerts were firing constantly mainly because:

  * The metrics endpoints were not reachable by the prometheus scraper. This was caused mainly by the `Service` of the application not exposing the metrics port correctly, making it impossible to be reached.
  * The application was not correctly configured to expose metrics on any endpoint. This has more to do with the application itself, in some cases we were missing flags in the workload commands, or configurations that the workload take (e.g. dex needs the `telemetry` value to be set in order to serve metrics).

* We were not catching this error in our CI because our test cases only check for the existence of the target. It is important that in the future we have re-usable test cases where we check for the actual alerts. In the case of `UnitUnavailable` it's as easy as querying for the application and asserting the result is `1`.

#### Future work

We have planned for improving our integration with COS for 24.04. Some of the things we can improved (based on my experience fixing this issue) are:

1. Documentation
  * This [guide](https://charmed-kubeflow.io/docs/integrate-with-cos) is a bit outdated and commands don't work, we need to update them
  * The guide is missing other charms that are already integrated with COS, like `istio-pilot`

2. Testing

  * We have a lot of duplications in our test cases for COS integration, we can put re-usable test-cases in charmed-kuebflow-chisme to keep consistency and accuracy
  * Test cases are not accurate, they are not asserting for things that we care about, like the unit is available

3. Services

  * We are not always exposing the metrics port in the app `Service`, which may cause issues when trying to scrape metrics. Using the `kubernetes_service_patch` library can help alleviate this.

#### PRs

* https://github.com/canonical/seldon-core-operator/pull/236
* https://github.com/canonical/notebook-operators/pull/332
* https://github.com/canonical/dex-auth-operator/pull/185
* https://github.com/canonical/metacontroller-operator/pull/101
* https://github.com/canonical/minio-operator/pull/157
* https://github.com/canonical/training-operator/pull/151

**Comment by DnPlas** [comment] 2024-02-16 12:08
All PRs have been merged, we can close this issue. Feel free to re-open if this still an issue.

**Closed by DnPlas** 2024-02-16 12:08 UTC
Labels: bug
