### ISSUE TITLE
Notebooks server 404

### ISSUE THREAD

**Issue by woropajj** [canonical/bundle-kubeflow#381] opened 2021-07-09 08:25 UTC
Installation steps:
`sudo snap install microk8s --classic`
`microk8s enable dashboard dns storage`
`microk8s enable metallb:192.168.1.10-192.168.1.50`
`microk8s enable kubeflow`

On Kubeflow dashboard, after clicking "Create a new Notebook server" I get the following page:
![Screenshot from 2021-07-09 10-19-22](https://user-images.githubusercontent.com/57800049/125047495-537c2980-e09f-11eb-8851-e0b61116149e.png)

`{
  "log": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", 
  "status": 404, 
  "success": false, 
  "user": "admin"
}`

Ran `microk8s inspect`, below is the file attached:
[inspection-report-20210709_100149.tar.gz](https://github.com/canonical/bundle-kubeflow/files/6789911/inspection-report-20210709_100149.tar.gz)

Any suggestions?

**Comment by nitesh31mishra** [comment] 2021-07-12 09:36
Even I am also having the same issue.... It's been a week now but couldn't find a solution to it..... 
It would be great if someone could please help in solving this issue ...
I have opened the same issue on the kubeflow repo, but I have not received any leads yet...

A similar issue is opened over here..
https://github.com/kubeflow/kubeflow/issues/6031

**Comment by Benjamin-Etheredge** [comment] 2021-07-13 16:21
I had this same issue with `microk8s enable kubeflow`. So I followed the charmed install guide of Kubeflow to install it on top of microk8s and ran into the same issue again. Based on the charmed install guide, I tried `juju deploy cs:jupyter-web`, and it seemed to resolve the issue.

**Comment by nitesh31mishra** [comment] 2021-07-13 17:18
It's nice... Actually, I have tried the same thing but I was not able to access the notebook.... Apart from running this` juju deploy cs:jupyter-web` you have done anything else ?? Like created any relation between services and all ???

**Comment by Benjamin-Etheredge** [comment] 2021-07-13 17:25
I had to do a ton of things just to get the charmed install to work. But nothing besides that to get notebooks up.
I used a mish-mash of https://www.kubeflow.org/docs/distributions/charmed/install-kubeflow/, https://charmed-kubeflow.io/docs/install, and https://www.youtube.com/watch?v=M_Ama8ZY8OQ. 
None of them worked on their own. I also had to use to skip steps before `juju bootstrap` and use `juju bootstrap microk8s micro` instead. It was messy. But again, that was just to get Kubeflow up. Notebooks came up after just using `juju deploy cs:jupyter-web`.

**Comment by Benjamin-Etheredge** [comment] 2021-07-14 16:44
I installed on microk8s running on Ubuntu 20.04 server. I used `cs:kubeflow`, not kubeflow-lite.

**Comment by lenaherrmann-dfki** [comment] 2021-07-15 13:57
Same bug here. 

Are there any solutions available?

**Comment by fengredrum** [comment] 2021-07-16 02:43
> I had to do a ton of things just to get the charmed install to work. But nothing besides that to get notebooks up.
> I used a mish-mash of https://www.kubeflow.org/docs/distributions/charmed/install-kubeflow/, https://charmed-kubeflow.io/docs/install, and https://www.youtube.com/watch?v=M_Ama8ZY8OQ.
> None of them worked on their own. I also had to use to skip steps before `juju bootstrap` and use `juju bootstrap microk8s micro` instead. It was messy. But again, that was just to get Kubeflow up. Notebooks came up after just using `juju deploy cs:jupyter-web`.

Same error.

Here is my installation steps:
`sudo snap install microk8s --classic`
`microk8s enable dashboard dns storage`
`microk8s enable metallb:192.168.1.10-192.168.1.50`
`microk8s config > ~/.kube/config`
`sudo snap install juju --classic`
`juju add-k8s myk8s`
`juju bootstrap myk8s my-controller`
`juju add-model kubeflow`
`juju deploy cs:kubeflow`
`juju deploy cs:jupyter-web`

After all the pods are running, notebook server still show the following message: `{ "log": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", "status": 404, "success": false, "user": "admin" }`

**Comment by fengredrum** [comment] 2021-07-16 02:52
@Benjamin-Etheredge Could you kindly tell us your installation steps and software versions? So we can follow up

**Comment by lenaherrmann-dfki** [comment] 2021-07-16 06:50
Hey, 

yesterday I installed an older version of that bundle, and it seems like some relations are missing. 

For example the virtualservice for jupiter-web is missing (besides others) 

My setup is the same as the one from @fengredrum .

**Comment by maxtaq** [comment] 2021-07-16 07:34
I have solved the problem in the following way.

1. first install it by following these steps
https://charmed-kubeflow.io/docs/install

2. and then do the following.
``` bash
juju deploy cs:jupyter-web
juju upgrade-charm jupyter-web --switch cs:jupyter-ui-10
```
"10" should be the appropriate version. At the moment it is 10.

Then I clicked on the Notebook in the kubeflow-dashboard and it came back.

3. if ImagePullBackOff error occurs.
The reason is that the DNS of the OS (Ubuntu) no longer works.
Please set 8.8.8.8, 8.8.4.4.

Successfully executed some simple python code.

Perhaps there are some steps I'm forgetting.
I haven't done a reproducibility test yet.

**Comment by lenaherrmann-dfki** [comment] 2021-07-16 08:20
Thanks @maxtaq, I'll give it a try.

**Comment by fengredrum** [comment] 2021-07-16 09:10
> I solved the problem in the following way.
> 
> 1. first install it by following these steps
>    https://charmed-kubeflow.io/docs/install
> 2. and then do the following.
> 
> ```shell
> juju deploy cs:jupyter-web
> juju upgrade-charm jupyter-web --switch cs:jupyter-ui-10
> ```
> 
> "10" should be the appropriate version. At the moment it is 10.
> 
> Then I clicked on the Notebook in the kubeflow-dashboard and it came back.
> 
> 1. if ImagePullBackOff error occurs.
>    The reason is that the DNS of the OS (Ubuntu) no longer works.
>    Please set 8.8.8.8, 8.8.4.4.
> 
> Successfully executed some simple python code.
> 
> Perhaps there are some steps I'm forgetting.
> I haven't done a reproducibility test yet.

Thanks for your suggestion. I've tried your method, but still got the same error 🙁

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/26370917/125923502-e3b48cee-46ad-4139-b928-31d4967ab022.png">

**Comment by nitesh31mishra** [comment] 2021-07-16 09:13
I was facing a similar issue in kubeflow 1.3 latest version.. but things were working in 1.2. I am currently working on 1.2

**Comment by fengredrum** [comment] 2021-07-16 09:17
> I was facing a similar issue in kubeflow 1.3 latest version.. but things were working in 1.2. I am currently working on 1.2

Do you know which juju bundle is corresponding to Kubeflow 1.2?😂😂😂

`juju deploy cs:bundle/kubeflow-269`

**Comment by lenaherrmann-dfki** [comment] 2021-07-16 09:20
Hey, 

Because it seems that there is no list of available bundles, I tried **kubeflow-245**.  But with that version the dex-auth deployment did not start at all.

**Comment by lenaherrmann-dfki** [comment] 2021-07-16 10:59
When you list the virtualservices after the installation

`microk8s kubectl get virtualservice -n kubeflow`

you can see that jupyter-web is not there

![image](https://user-images.githubusercontent.com/85176444/125937474-9ad6408b-3b62-4fdb-b772-18d00af6e6d7.png)

How can jupyter-web be integrated here properly?

**Comment by ca-scribner** [comment] 2021-07-16 20:56
I hit the same issue and @maxtaq 's solution solved it for me except that my bundle version I had deployed uses the `jupyter-ui` charm and not `jupyter-web` (I believe older bundles used `jupyter-web`, but the charm has been renamed to `jupyter-ui`).  

`juju status` showed I was using `jupyter-ui` version 9.  Updating to the current version (10) using `juju refresh jupyter-ui --revision 10` and waiting for things to download/relate (watch `juju debug-log jupyter-ui`) worked for me.

**Comment by fengredrum** [comment] 2021-07-17 02:56
> I hit the same issue and @maxtaq 's solution solved it for me except that my bundle version I had deployed uses the `jupyter-ui` charm and not `jupyter-web` (I believe older bundles used `jupyter-web`, but the charm has been renamed to `jupyter-ui`).
> 
> `juju status` showed I was using `jupyter-ui` version 9. Updating to the current version (10) using `juju refresh jupyter-ui --revision 10` and waiting for things to download/relate (watch `juju debug-log jupyter-ui`) worked for me.

Thanks a lot!!! This solution works for me.🎉🎉🎉

Here is my whole setup:
Ubuntu 20.04 on AWS EC2 with 4 CPUs, 16Gb RAM and 100Gb disk space
`sudo snap install microk8s --classic`
`microk8s enable dashboard dns storage`
`microk8s enable metallb:10.64.140.43-10.64.140.49`
`microk8s config > ~/.kube/config`
`sudo snap install juju --classic`
`juju add-k8s myk8s`
`juju bootstrap myk8s my-controller`
`juju add-model kubeflow`
`juju deploy cs:bundle/kubeflow-269`
`juju refresh jupyter-ui --revision 10`

The Notebook Server works perfectly so far.

**Comment by ca-scribner** [comment] 2021-07-17 11:40
Awesome! Glad someone else can reproduce too :D

**Comment by knkski** [comment] 2021-07-28 01:59
This should now be fixed in the stable version of Charmed Kubeflow by #380. https://github.com/ubuntu/microk8s/pull/2480 will bring the fix into `microk8s enable kubeflow`.

Closing this issue since it should now be fixed, feel free to reopen if you still have any issues with it

**Closed by knkski** 2021-07-28 01:59 UTC

**Comment by yurkoff-mv** [comment] 2021-10-14 12:54
The problem is still present in microk8s v1.21.5:
```
sudo snap install microk8s --classic --channel=1.21/stable
microk8s enable dns dashboard storage gpu registry istio
microk8s enable kubeflow
```

**Comment by maxtaq** [comment] 2021-10-15 01:20
> The problem is still present in microk8s v1.21.5:
> 
> ```
> sudo snap install microk8s --classic --channel=1.21/stable
> microk8s enable dns dashboard storage gpu registry istio
> microk8s enable kubeflow
> ```

This code may fix it.
```
microk8s.juju remove-application jupyter-ui
microk8s.juju deploy jupyter-ui-10
microk8s.juju relate jupyter-ui istio-pilot
```

**Comment by yurkoff-mv** [comment] 2021-10-15 06:03
Thank you it is working for me!
