### ISSUE TITLE
No guide avilable to install Kubeflow offline on Microk8s in a corporate envirement behind proxy

### ISSUE THREAD

**Issue by vivekjainmaiet** [canonical/bundle-kubeflow#540] opened 2023-01-30 18:18 UTC

**Comment by ca-scribner** [comment] 2023-02-14 22:36
Hi @vivekjainmaiet, does [this guide](https://charmed-kubeflow.io/docs/deploy-kubeflow-on-microk8s-behind-a-web-proxy) address what you need?

**Comment by ca-scribner** [comment] 2023-02-14 22:37
It isn't quite what you're looking for I dont think as it is more aimed at a proxy but still having connectivity

**Comment by DnPlas** [comment] 2023-03-13 09:41
Duplicate of #497

**Closed by DnPlas** 2023-03-13 09:41 UTC
Labels: enhancement, docs, Kubeflow 1.7
