### ISSUE TITLE
NodePort support for istio-ingressgateway

### ISSUE THREAD

**Issue by SMAK1993** [canonical/bundle-kubeflow#518] opened 2022-11-14 22:52 UTC
The istio-ingressgateway charm should also support a NodePort option in environments without service type LoadBalancer.

**Comment by ca-scribner** [comment] 2022-11-17 16:53
I think this is a duplicate of [this issue on the istio board](https://github.com/canonical/istio-operators/issues/126).  I'm linking it there and closing this one, but if I misunderstood please reopen!

**Closed by ca-scribner** 2022-11-17 16:53 UTC
