### ISSUE TITLE
Error installing microk8s with juju 2.8

### ISSUE THREAD

**Issue by amr-elsehemy** [canonical/bundle-kubeflow#219] opened 2020-07-04 12:07 UTC
Hello, 
I've been attempting the installation in the past few days again and it seems like there are new unaddressed issues between juju 2.8 and microk8s

here's what happens when I run this line
` sudo snap install microk8s --classic`

after installing juju and cd into `bundle-kubeflow` dir

`error: cannot perform the following tasks
 Run hook connect-plug-peers of snap "juju" (run hook "connect-plug-peers": 
error: error running snapctl: cannot perform the following tasks:
start of [juju.fetch-oci] (# systemctl start snap.juju.fetch-oci.service
Job for snap.juju.fetch-oci.service failed because the control process exited with error code.
See "systemctl status snap.juju.fetch-oci.service" and "journalctl -xe" for details.
)
 start of [juju.fetch-oci] (exit status 1)
)
`

I tried falling back to juju 2.7 but I'm facing other issues with cert-manager-webhook-operator pod can't be located ..

attached a photo to show the problem,

is there any solution to these problems either for v2.7 or v2.8

![juju-issue](https://user-images.githubusercontent.com/2354585/86512135-a3c30a80-bdff-11ea-8325-70cc31ca6a79.png)

**Comment by knkski** [comment] 2020-07-08 15:07
@amr-elsehemy: This is due to this issue: https://bugs.launchpad.net/juju/+bug/1881769

That should be fixed in the Juju 2.8.1 snap, but in the meantime, downgrading the juju snap (or uninstalling it) will fix the problem:

    sudo snap switch juju --channel 2.7/stable
    sudo snap refresh

**Comment by knkski** [comment] 2020-07-08 15:09
As far as the issue with cert-manager goes, it looks like you're deploying with the `scripts/cli.py` script from this repo. You'll want to make sure you're using the latest version (`git checkout master && git pull`), as cert-manager has been moved to a separate bundle:

    https://github.com/juju-solutions/bundle-cert-manager

**Comment by DomFleischmann** [comment] 2021-06-25 09:46
Wit this issue being almost 1 year old and juju being now on 2.9 we can close this issue.

If you are able to reproduce this in the latest kubeflow bundle and the issue is still relevant feel free to reopen it.

**Closed by DomFleischmann** 2021-06-25 09:46 UTC
