### ISSUE TITLE
Pipeline logs are disappearing after 24h

### ISSUE THREAD

**Issue by AxoyTO** [canonical/bundle-kubeflow#1120] opened 2024-10-18 06:40 UTC
### Bug Description

After 24 hours of creation, all logs belonging to a pipeline run disappear from the Charmed Kubeflow UI, despite the logs still being present in MinIO/mlpipeline (AWS S3). This leads to difficulty in troubleshooting and tracking the progress or failures of pipeline runs after the 24-hour period.

![image](https://github.com/user-attachments/assets/83383ffa-13b1-430a-a424-4ed2c978e1af)

```# With necessary env variables being set
!aws --endpoint-url $MINIO_ENDPOINT_URL s3 ls s3://mlpipeline
                           [...]
                           PRE addition-pipeline-4g94d/
                           PRE addition-pipeline-4qwt4/
                           PRE download-preprocess-train-deploy-pipeline-8wjv9/
                           PRE mnist-pipeline-fcmgr/
                           [...]
!aws --endpoint-url $MINIO_ENDPOINT_URL s3 ls s3://mlpipeline/download-preprocess-train-deploy-pipeline-8wjv9/download-preprocess-train-deploy-pipeline-8wjv9-system-container-impl-1190848556/
2024-10-15 15:27:49      10796 main.log
```

### To Reproduce

1. Deploy Charmed Kubeflow 1.9 using Juju.
2. Create a pipeline and run it.
3. After the run completes, observe that logs are available in the Kubeflow UI.
4. Wait for 24 hours after the pipeline run completes.
5. Attempt to view the pipeline logs in the UI again.
**Expected**: Logs should still be accessible.
**Actual**: Logs are no longer visible in the UI, but are still present in the underlying MinIO/mlpipeline (AWS S3).

### Environment

CKF: 1.9/stable
minio: ckf-1.9/stable
argo-controller: 3.4/stable
Juju: 3.5.4
See the full bundle on: https://paste.ubuntu.com/p/NXXFhDqmVn/

### Relevant Log Output

```shell
<none>
```

### Additional Context

Notebook that is used to create a pipeline, which was ran on a notebook server with a GPU:
```py
import kfp
from kfp import dsl, kubernetes

@dsl.component(
    base_image="tensorflow/tensorflow:latest-gpu",
    # packages_to_install=["tensorflow"]
)
def foo():
    '''Calculates sum of two arguments'''
    print("GPU Test")
    import tensorflow as tf
    print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
    print("GPU Test")


@dsl.pipeline(
    name='Addition pipeline',
    description='An example pipeline that performs addition calculations.')
def foo_pipeline():
    task = (foo()
            .set_cpu_request(str(2))
            .set_cpu_limit(str(4))
            .set_memory_request("2Gi")
            .set_memory_limit("4Gi")
            .set_gpu_limit("1")
            .set_accelerator_type("nvidia.com/gpu")
           )

    task = kubernetes.set_image_pull_policy(task=task, policy="Always")

    task = kubernetes.add_toleration(
        task=task,
        key="sku",
        operator="Equal",
        value="gpu",
        effect="NoSchedule",
    )

namespace = "admin"

client = kfp.Client()

run = client.create_run_from_pipeline_func(
    run_name="gpu_test",
    pipeline_func=foo_pipeline,
    namespace=namespace,
    experiment_name="gpu-foo")
```

Could be related to upstream: https://github.com/kubeflow/pipelines/issues/7617

**Comment by kimwnasptd** [comment] 2024-10-30 14:36
First of all I managed to reproduce this by
1. Creating a run
2. Waiting for about a day

The underlying Argo Workflow was fully deleted, alongside all the Pipeline Pods in the user namespace. Then in the UI I would see the error above

**Comment by kimwnasptd** [comment] 2024-10-30 14:45
Also with a quick research in the upstream project I see a similar issue raised 
https://github.com/kubeflow/pipelines/issues/8935

But that seems to be resolved, and the PR of the fix is merged in KFP 2.2.0, which is used by Kubeflow 1.9.

**Comment by kimwnasptd** [comment] 2024-11-08 12:53
Looking a bit more into the source code of KFP I found this `ARGO_ARCHIVE_LOGS` env var that is set by default to false (!)
https://github.com/kubeflow/pipelines/blob/2.3.0/frontend/server/configs.ts#L89

Enabling this env var results in now the logs to fail with a different error
```
Error response: Could not get main container logs: S3Error: The specified key does not exist.
```

Which means now the `ml-pipeline-ui` Pod (`kubeflow` namespace) is trying also to reach MinIO. This makes sense since after inspecting more the source code it looks like if this setting is enabled then the logs handler will try to talk to MinIO
1. https://github.com/kubeflow/pipelines/blob/2.3.0/frontend/server/handlers/pod-logs.ts#L61
2. https://github.com/kubeflow/pipelines/blob/2.3.0/frontend/server/app.ts#L202

**Comment by kimwnasptd** [comment] 2024-11-08 13:52
After looking at the logs from `ml-pipeline-ui` I see the following:
```
Getting logs for pod:tutorial-data-passing-8dntv-system-container-impl-2572032214 from mlpipeline/logs/tutorial-data-passing-8dntv-system-container-impl/tutorial-data-passing-8dntv-system-container-impl-2572032214/main.log
```

But this is wrong, since the path that the logs are exposed in MinIO is the following:
```
mlpipeline/artifacts/tutorial-data-passing-8dntv/2024/11/08/tutorial-data-passing-8dntv-system-container-impl-2572032214/main.log
```

So the kfp-ui is not calculating the path for the logs in KFP 2.2.0

**Comment by kimwnasptd** [comment] 2024-11-08 16:17
After looking closer at the source code it looks like this was a bug in V2 that exists all the way to KFP v2.2.0. This is resolved though in upstream in the following https://github.com/kubeflow/pipelines/pull/11010

Although after trying the v2.3.0 image then the UI pod server process was restarting and I was seeing a lot of errors like the following:
```
/server/node_modules/node-fetch/lib/index.js:1491
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to http://metadata/computeMetadata/v1/instance/attributes/cluster-name failed, reason: getaddrinfo EAI_AGAIN metadata
    at ClientRequest.<anonymous> (/server/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:517:28)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
```

This looks like to be from a specific GKE handler of KFP caused from
https://github.com/kubeflow/pipelines/blob/2.3.0/frontend/server/app.ts#L237-L238

**Comment by kimwnasptd** [comment] 2024-11-08 16:23
In the end I managed to get the logs working by:
1. Updating the image of the UI to `gcr.io/ml-pipeline/frontend:2.3.0`
2. Adding the env var `ARGO_ARCHIVE_LOGS: "true"`
3. Adding the env var `DISABLE_GKE_METADATA: "true"`

**Comment by NohaIhab** [comment] 2024-12-03 11:19
Closed by https://github.com/canonical/kfp-operators/pull/605 and https://github.com/canonical/argo-operators/pull/208
Fix is now released to `1.9/stable` bundle, check out the [announcement](https://discourse.charmhub.io/t/charmed-kubeflow-1-9-updated-to-use-kfp-2-3/16073)

**Closed by NohaIhab** 2024-12-03 11:19 UTC
Labels: bug

**Comment by swasenius** [comment] 2025-02-07 09:48
When you upgrade Kubeflow to 1.9, these images are not taken into use automatically (here it should use 2.3.0)

kubectl describe replicasets -n xyz|grep 2.0.3                                                    
    Image:      gcr.io/ml-pipeline/frontend:2.0.3
    Image:      gcr.io/ml-pipeline/frontend:2.0.3
    Image:      gcr.io/ml-pipeline/visualization-server:2.0.3
    Image:      gcr.io/ml-pipeline/visualization-server:2.0.3

Possibly an improvement idea here, since you need to rollout the new 2.3.0 images manually I suppose.

**Comment by kimwnasptd** [comment] 2025-02-07 20:33
@swasenius could you verify what charm track you are using? In our upgrade instructions we ask users to go for the newest `2.3` track
https://charmed-kubeflow.io/docs/upgrade-18-19

What do you see with `juju status`?
