### ISSUE TITLE
Error when installing Kubeflow with microk8s

### ISSUE THREAD

**Issue by jtfogarty** [canonical/bundle-kubeflow#259] opened 2020-11-02 20:44 UTC
I'm see the below error when I attempt to install Kubeflow.

It seems that it cannot find the .kube/config file. (which is not there by the way.  not sure how microk8s does this)

```
microk8s enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for DNS and storage plugins to finish setting up
Kubeflow could not be enabled:
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?

Command '('microk8s-kubectl.wrapper', 'wait', '--for=condition=available', '-nkube-system', 'deployment/coredns', 'deployment/hostpath-provisioner', '--timeout=10m')' returned no
n-zero exit status 1
Failed to enable kubeflow
ubuntu@node05ob96:~$ microk8s kubectl get nodes
NAME         STATUS   ROLES    AGE   VERSION 
node02ob96   Ready    <none>   20m   v1.19.2-34+1b3fa60b402c1c
node01ob96   Ready    <none>   18m   v1.19.2-34+1b3fa60b402c1c
node05ob96   Ready    <none>   42m   v1.19.2-34+1b3fa60b402c1c
```

**Comment by RFMVasconcelos** [comment] 2020-11-02 20:51
Thank you @jtfogarty for this! 

/assign @knkski

**Comment by knkski** [comment] 2020-11-09 17:07
@jtfogarty: The fastest way to fix this is with `sudo snap switch microk8s --channel 1.18/stable && sudo snap refresh`.

cc @ktsakalozos, as this looks like a 1.19 / calico sort of issue

**Comment by DomFleischmann** [comment] 2021-06-25 09:54
With the currently recommended microk8s versions for the Kubeflow addon being 1.20 and 1.21 we can close this issue.

If you are able to reproduce this in the latest kubeflow bundle and the issue is still relevant feel free to reopen it.

**Closed by DomFleischmann** 2021-06-25 09:54 UTC
